### ISSUE TITLE
feat(Schematics): extend/add to a schematic from another collection

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/devkit#262] opened 2017-11-06 16:25 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] feature request
```

### Area
```
- [x] schematics
```

### Desired functionality

Right now I know we can do something like 
```
component: {
    extends: '@schematics/angular'
}
```

But I don't think we can add functionality upon this

### Mention any other details that might be useful
USE CASE:

Example: I want to create a schematic that would be running like `ng new angular-jest --collection jest_collection_name"`

and it would create a new angular project using `@schematics/angular`, and then add more files that would make this application support running tests using jest.

**Comment by mohammedzamakhan** [comment] 2017-11-07 18:21
@Brocco

**Comment by hansl** [comment] 2017-11-22 18:46
Dupe of https://github.com/angular/devkit/issues/34

**Closed by hansl** 2017-11-22 18:46 UTC
