### ISSUE TITLE
ng update @angular/core errors when peer dependency of @angular/core uses ">=x.x.x" type syntax

### ISSUE THREAD

**Issue by danielwstrimpel** [angular/devkit#889] opened 2018-05-10 18:16 UTC
### Bug Report or Feature Request (mark with an # x)

    - [x] bug report -> please search issues before submitting
    - [ ] feature request

### Area
    - [ ] devkit
    - [x] schematics

### Versions

Angular CLI: 1.6.7

### Repro steps
Create an Angular 5 app using the CLI, install a package that uses peer dependency syntax like `>=x.x.x`, and then try to upgrade to Angular 6.

- Run `ng new repro` -> then change directory to repro
- Run `npm install @angular/cli@latest`
- Run `ng update @angular/cli`
- Run `npm install typescript@2.7.2 ng2-completer`
- Run `ng update @angular/core`

Peer dependencies in `ng2-completer` look like:

```json
"peerDependencies": {
    "@angular/common": ">=2.1.0",
    "@angular/compiler": ">=2.1.0",
    "@angular/core": ">=2.1.0",
    "@angular/forms": ">=2.1.0",
    "@angular/http": ">=2.1.0",
    "@angular/platform-browser": ">=2.1.0",
    "@angular/platform-browser-dynamic": ">=2.1.0",
    "rxjs": ">=5.1.0",
    "zone.js": ">=0.7.2"
},
```

### The log given by the failure
>Invalid range: ">=2.1.0"

### Desired functionality

The update should proceed perfectly fine as any updates to `@angular/core` that are greater than or equal to `2.1.0` are acceptable.

### Mention any other details that might be useful

Digging through the source code to determine where the error was coming from, I think that the issue is because of the following code:

https://github.com/angular/devkit/blob/e6379b12802e7942c6528716ebc8d2a03c5c9d0a/packages/schematics/update/update/index.ts#L34-L49

Specifically, it is the following line:

https://github.com/angular/devkit/blob/e6379b12802e7942c6528716ebc8d2a03c5c9d0a/packages/schematics/update/update/index.ts#L38

The `semver.gtr(...)` method will "[Determine if version is greater than all the versions possible in the range.](https://github.com/npm/node-semver/blob/44cbc8482ac4f0f8d2de0abb7f8808056d2d55f9/semver.js#L1221-L1225)" If a library has an `@angular/core` peer dependency range that is open ended (e.g. uses >= x.x.x syntax) it is not possible to find a version that will be greater than the range.

```js
semver.gtr('6.0.0', '>=2.1.0'); // false
semver.satisfies('6.0.0', '>=2.1.0'); // true
```

**Comment by clydin** [comment] 2018-05-11 18:16
Duplicate of angular/angular-cli#10621

**Closed by clydin** 2018-05-11 18:16 UTC
