### ISSUE TITLE
Using externalSchematic breaks debug mode

### ISSUE THREAD

**Issue by maciejtreder** [angular/devkit#635] opened 2018-04-05 21:19 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x ] devkit
- [  ] schematics
```

### Versions

Node: v8.5.0
npm: 5.3.0
OS: macOS El Capitan

@schematics/schematics@0.5.1
@angular-devkit/schematics-cli@0.4.7

### Repro steps
```
import { chain, externalSchematic, Rule } from '@angular-devkit/schematics';

export function application(options: any): Rule {
  return chain([
      externalSchematic('@schematics/angular', 'application', options)
    ]);
}
```

### The log given by the failure
```
An error occured:
Error: Could not find (undefined)
    at Object.getWorkspace (/Users/mtreder/Documents/private/work/angular-universal-serverless/schematics/node_modules/@schematics/angular/utility/config.js:14:15)
    at /Users/mtreder/Documents/private/work/angular-universal-serverless/schematics/node_modules/@schematics/angular/application/index.js:241:36
    at MergeMapSubscriber.input.pipe.mergeMap_1.mergeMap.inputTree [as project] (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/src/rules/call.js:80:24)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/Subscriber.js:93:18)
    at ScalarObservable._subscribe (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/observable/ScalarObservable.js:49:24)
    at ScalarObservable.Observable._trySubscribe (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/Observable.js:172:25)
    at ScalarObservable.Observable.subscribe (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/Observable.js:160:93)
    at MergeMapOperator.call (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/operators/mergeMap.js:87:23)
```

### Desired functionality
Normally the list of files in staging is displayed.

**Comment by hansl** [comment] 2018-04-12 18:00
Hi @maciejtreder, Marking this as nice to have for the release, but it's definitely an issue we want to fix as soon as possible. Thanks!

**Comment by LFeh** [comment] 2018-04-20 23:07
Same here 😢

**Comment by nikiforosFreespirit** [comment] 2018-05-14 15:04
If it can provide any assistance I experience a similar issue as the logger but with different version and slightly different stack trace. Here are the informations:

OS: Ubuntu 16.04 LTS

Versions: v10.1.0 (node), 6.0.1 (npm), 0.6.1 (@angular-devkit/schematics@ and @schematics/angular)

Stack trace:
```
An error occured:
Error: Could not find (undefined)
    at Object.getWorkspace (/home/mcaci/Code/firstSchematics/node_modules/@schematics/angular/utility/config.js:14:15)
    at /home/mcaci/Code/firstSchematics/node_modules/@schematics/angular/application/index.js:213:36
    at MergeMapSubscriber.input.pipe.operators_1.mergeMap.inputTree [as project] (/home/mcaci/Code/node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/src/rules/call.js:77:24)
    at MergeMapSubscriber._tryNext (/home/mcaci/Code/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/home/mcaci/Code/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/home/mcaci/Code/node_modules/rxjs/internal/Subscriber.js:103:18)
    at Observable._subscribe (/home/mcaci/Code/node_modules/rxjs/internal/observable/scalar.js:6:20)
    at Observable.subscribe (/home/mcaci/Code/node_modules/rxjs/internal/Observable.js:162:69)
    at MergeMapOperator.call (/home/mcaci/Code/node_modules/rxjs/internal/operators/mergeMap.js:87:23)
    at Observable.subscribe (/home/mcaci/Code/node_modules/rxjs/internal/Observable.js:159:22)
```

The code to reproduce the issue is the same and it seems by looking at the code in ...node_modules/@schematics/angular/utility/config.js that it wants to read the schematic from a file called angular.json or .angular.json but doesn't find it in the schematic 'application' so it's not able to read it and because of this it raises the exception

**Comment by alexeagle** [comment] 2018-09-04 23:20
This issue was moved to angular/angular-cli#12125

**Closed as completed by alexeagle** 2018-09-04 23:20 UTC
Labels: priority3: nice to have
