### ISSUE TITLE
Error: Path "/app/app.module.ts" does not exist.

### ISSUE THREAD

**Issue by Robinyo** [angular/devkit#351] opened 2017-12-30 02:44 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```
### Desired functionality
I followed the steps in this [post](https://blog.angularindepth.com/creating-your-own-application-template-for-angular-cli-95e22319cc24) to create an application template for the angular-cli.

For example:

 `ng new --collection=@ionic-starter/blank myApp`

Just wondering if/when the `require.resolve()` [issue](https://stackoverflow.com/questions/46429693/angular-cli-custom-schematics-collection) will be addressed?

So we can use symbolic links, for example: 
```
ln -s /Users/rob/workspace/ionic-starter /usr/local/lib/node_modules/@angular/cli/node_modules/@ionic-starter
```
Ref:
- https://stackoverflow.com/questions/46429693/angular-cli-custom-schematics-collection 
- https://robferguson.org/blog/2017/12/31/the-future-of-the-ionic-cli/

**Comment by Brocco** [comment] 2018-01-30 20:51
This is a duplicate of angular/angular-cli#8989
and resolved via PR #418

**Closed by Brocco** 2018-01-30 20:51 UTC
Labels: comp: angular-devkit/schematics, type: bug
