### ISSUE TITLE
Offer a schematics API for doing npm/yarn installs

### ISSUE THREAD

**Issue by StephenFluin** [angular/devkit#216] opened 2017-10-18 21:25 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x] feature request
```

### Area
```
- [x] schematics
```

I would like to be able to call a function within schematics, and have schematics install via my chosen package manager. This would also allow tools like StackBlitz to override / patch these methods and perform their own package installation / setup.

**Comment by hansl** [comment] 2017-10-30 22:00
Duplicate of #12?

**Closed by hansl** 2017-10-30 22:00 UTC
